#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.1 effective-5.10 (swiftlang-6.1.0.110.21 clang-1700.0.13.3)
#ifndef SHOPLIVESHORTFORMEDITORSDK_SWIFT_H
#define SHOPLIVESHORTFORMEDITORSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ShopLiveShortformEditorSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSCoder;
SWIFT_CLASS("_TtC26ShopLiveShortformEditorSDK29SLBackspaceDetectingTextField")
@interface SLBackspaceDetectingTextField : UITextField
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)deleteBackward;
- (void)paste:(id _Nullable)sender;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class UIColor;
@class UIEvent;
SWIFT_CLASS("_TtC26ShopLiveShortformEditorSDK11SLWSTagView")
@interface SLWSTagView : UIView <UITextInputTraits>
@property (nonatomic, strong) UIColor * _Null_unspecified tintColor;
@property (nonatomic) UITextAutocapitalizationType autocapitalizationType;
@property (nonatomic) UITextAutocorrectionType autocorrectionType;
@property (nonatomic) UITextSpellCheckingType spellCheckingType;
@property (nonatomic) UIKeyboardType keyboardType;
@property (nonatomic) UIKeyboardAppearance keyboardAppearance;
@property (nonatomic) UIReturnKeyType returnKeyType;
@property (nonatomic) BOOL enablesReturnKeyAutomatically;
@property (nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (CGSize)sizeThatFits:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (void)layoutSubviews;
@property (nonatomic, readonly) BOOL canBecomeFirstResponder;
- (BOOL)becomeFirstResponder SWIFT_WARN_UNUSED_RESULT;
- (BOOL)resignFirstResponder SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)hitTest:(CGPoint)point withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class NSString;
@interface SLWSTagView (SWIFT_EXTENSION(ShopLiveShortformEditorSDK)) <UIKeyInput>
@property (nonatomic, readonly) BOOL hasText;
- (void)insertText:(NSString * _Nonnull)text;
- (void)deleteBackward;
@end

@class UIFont;
IB_DESIGNABLE
SWIFT_CLASS("_TtC26ShopLiveShortformEditorSDK13SLWSTagsField")
@interface SLWSTagsField : UIScrollView
/// Background color for tag view in normal (non-selected) state.
@property (nonatomic, strong) IBInspectable UIColor * _Null_unspecified tintColor;
/// Text color for tag view in normal (non-selected) state.
@property (nonatomic, strong) IBInspectable UIColor * _Nullable textColor;
/// Background color for tag view in normal (selected) state.
@property (nonatomic, strong) IBInspectable UIColor * _Nullable selectedColor;
/// Text color for tag view in normal (selected) state.
@property (nonatomic, strong) IBInspectable UIColor * _Nullable selectedTextColor;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull delimiter;
@property (nonatomic) IBInspectable BOOL isDelimiterVisible;
/// Whether the text field should tokenize strings automatically when the keyboard is dismissed.
@property (nonatomic) IBInspectable BOOL shouldTokenizeAfterResigningFirstResponder;
@property (nonatomic) IBInspectable CGFloat maxHeight;
/// Max number of lines of tags can display in SLWSTagsField before its contents become scrollable. Default value is 0, which means SLWSTagsField always resize to fit all tags.
@property (nonatomic) IBInspectable NSInteger numberOfLines;
/// Whether or not the SLWSTagsField should become scrollable
@property (nonatomic) IBInspectable BOOL enableScrolling;
@property (nonatomic) IBInspectable CGFloat cornerRadius;
@property (nonatomic) IBInspectable CGFloat borderWidth;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable borderColor;
@property (nonatomic) UIEdgeInsets layoutMargins;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull placeholder;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable placeholderColor;
@property (nonatomic, strong) IBInspectable UIFont * _Nullable placeholderFont;
@property (nonatomic) IBInspectable BOOL placeholderAlwaysVisible;
@property (nonatomic) IBInspectable BOOL readOnly;
@property (nonatomic) UIEdgeInsets contentInset;
@property (nonatomic) IBInspectable CGFloat spaceBetweenTags;
@property (nonatomic) IBInspectable CGFloat spaceBetweenLines;
@property (nonatomic, readonly) BOOL isFirstResponder;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (CGSize)sizeThatFits:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
- (void)layoutSubviews;
- (void)reloadInputViews;
- (void)onTextFieldDidChange:(id _Nonnull)sender;
@end

@interface SLWSTagsField (SWIFT_EXTENSION(ShopLiveShortformEditorSDK))
- (UIView * _Nullable)hitTest:(CGPoint)point withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
@end

@interface SLWSTagsField (SWIFT_EXTENSION(ShopLiveShortformEditorSDK)) <UITextFieldDelegate>
- (BOOL)textFieldShouldBeginEditing:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
- (BOOL)textFieldShouldEndEditing:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidEndEditing:(UITextField * _Nonnull)textField;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
@end

@interface SLWSTagsField (SWIFT_EXTENSION(ShopLiveShortformEditorSDK))
@property (nonatomic, readonly, strong) UIView * _Nullable inputAccessoryView SWIFT_DEPRECATED_MSG("Use 'inputFieldAccessoryView' instead");
@end

@class UIViewController;
@class ShopLiveCommonError;
@class UIImage;
@class ShopliveEditorResultData;
SWIFT_PROTOCOL("_TtP26ShopLiveShortformEditorSDK27ShopLiveCoverPickerDelegate_")
@protocol ShopLiveCoverPickerDelegate
@optional
- (void)onShopLiveCoverPickerErrorWithPicker:(UIViewController * _Nullable)picker error:(ShopLiveCommonError * _Nonnull)error;
- (void)onShopLiveCoverPickerCoverImageSuccessWithPicker:(UIViewController * _Nullable)picker image:(UIImage * _Nullable)image;
- (void)onShopLiveCoverPickerUploadSuccessWithPicker:(UIViewController * _Nullable)picker result:(ShopliveEditorResultData * _Nullable)result;
- (void)onShopLiveCoverPickerCancelledWithPicker:(UIViewController * _Nullable)picker;
- (void)onShopLiveCoverPickerOnEventWithPicker:(UIViewController * _Nullable)picker name:(NSString * _Nonnull)name payload:(NSDictionary<NSString *, id> * _Nullable)payload;
@end

SWIFT_CLASS("_TtC26ShopLiveShortformEditorSDK19ShopLiveMediaPicker")
@interface ShopLiveMediaPicker : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSURL;
SWIFT_PROTOCOL("_TtP26ShopLiveShortformEditorSDK27ShopLiveMediaPickerDelegate_")
@protocol ShopLiveMediaPickerDelegate
@optional
- (void)onShopLiveMediaPickerErrorWithPicker:(UIViewController * _Nullable)picker error:(ShopLiveCommonError * _Nonnull)error;
- (void)onShopLiveMediaPickerDidPickVideoWithPicker:(UIViewController * _Nullable)picker absoluteUrl:(NSURL * _Nonnull)absoluteUrl relativeUrl:(NSURL * _Nonnull)relativeUrl;
- (void)onShopLiveMediaPickerDidPickImageWithPicker:(UIViewController * _Nullable)picker imageUrl:(NSURL * _Nonnull)imageUrl;
- (void)onShopLiveMediaPickerCancelledWithPicker:(UIViewController * _Nullable)picker;
- (void)onShopLiveMediaPickerOnEventWithPicker:(UIViewController * _Nullable)picker name:(NSString * _Nonnull)name payload:(NSDictionary<NSString *, id> * _Nullable)payload;
@end

SWIFT_PROTOCOL("_TtP26ShopLiveShortformEditorSDK31ShopLiveShortformEditorDelegate_")
@protocol ShopLiveShortformEditorDelegate
@optional
- (void)onShopLiveShortformEditorErrorWithError:(ShopLiveCommonError * _Nonnull)error;
- (void)onShopLiveShortformEditorVideoConvertSuccessWithVideoPath:(NSString * _Nonnull)videoPath;
- (void)onShopLiveShortformEditorCoverImageSuccessWithImage:(UIImage * _Nullable)image;
- (void)onShopLiveShortformEditorUploadSuccessWithResult:(ShopliveEditorResultData * _Nullable)result;
- (void)onShopLiveShortformEditorClosed;
- (void)onShopLiveShortformEditorOnEventWithName:(NSString * _Nonnull)name payload:(NSDictionary<NSString *, id> * _Nullable)payload;
@end

@class NSBundle;
SWIFT_CLASS("_TtC26ShopLiveShortformEditorSDK35ShopLiveShortformEditorSDKResources")
@interface ShopLiveShortformEditorSDKResources : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSBundle * _Nonnull bundle;)
+ (NSBundle * _Nonnull)bundle SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC26ShopLiveShortformEditorSDK25ShopLiveShortformUploader")
@interface ShopLiveShortformUploader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_PROTOCOL("_TtP26ShopLiveShortformEditorSDK33ShopLiveShortformUploaderDelegate_")
@protocol ShopLiveShortformUploaderDelegate
@optional
- (void)onShopLiveShortformUploaderOpenVideoEditor;
- (void)onShopLiveShortformUploaderUploadSuccess;
- (void)onShopLiveShortformUploaderPlayPreviewWithRoot:(UIViewController * _Nonnull)root url:(NSString * _Nonnull)url;
- (void)onShopLiveShortformUploaderOpenCoverPickerWithEditor:(UIViewController * _Nullable)editor shortsId:(NSString * _Nonnull)shortsId videoUrl:(NSString * _Nullable)videoUrl;
- (void)onShopLiveShortformUploaderEventWithCommand:(NSString * _Nonnull)command payload:(NSDictionary<NSString *, id> * _Nullable)payload;
- (void)onShopLiveShortformUploaderErrorWithError:(ShopLiveCommonError * _Nonnull)error;
@end

SWIFT_PROTOCOL("_TtP26ShopLiveShortformEditorSDK40ShopLiveShortformUploaderMessageDelegate_")
@protocol ShopLiveShortformUploaderMessageDelegate
@optional
- (void)uploadWithId:(NSString * _Nonnull)id;
- (void)successCoverChange;
@end

SWIFT_PROTOCOL("_TtP26ShopLiveShortformEditorSDK27ShopLiveVideoEditorDelegate_")
@protocol ShopLiveVideoEditorDelegate
@optional
- (void)onShopLiveVideoEditorErrorWithEditor:(UIViewController * _Nullable)editor error:(ShopLiveCommonError * _Nonnull)error;
- (void)onShopLiveVideoEditorVideoConvertSuccessWithEditor:(UIViewController * _Nullable)editor videoPath:(NSString * _Nonnull)videoPath;
- (void)onShopLiveVideoEditorUploadSuccessWithEditor:(UIViewController * _Nullable)editor result:(ShopliveEditorResultData * _Nullable)result;
- (void)onShopLiveVideoEditorCancelledWithEditor:(UIViewController * _Nullable)editor;
- (void)onShopLiveVideoEditorOnEventWithEditor:(UIViewController * _Nullable)editor name:(NSString * _Nonnull)name payload:(NSDictionary<NSString *, id> * _Nullable)payload;
@end

SWIFT_CLASS("_TtC26ShopLiveShortformEditorSDK26ShopLiveVideoUploadPreview")
@interface ShopLiveVideoUploadPreview : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC26ShopLiveShortformEditorSDK24ShopliveEditorResultData")
@interface ShopliveEditorResultData : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.1 effective-5.10 (swiftlang-6.1.0.110.21 clang-1700.0.13.3)
#ifndef SHOPLIVESHORTFORMEDITORSDK_SWIFT_H
#define SHOPLIVESHORTFORMEDITORSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ShopLiveShortformEditorSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSCoder;
SWIFT_CLASS("_TtC26ShopLiveShortformEditorSDK29SLBackspaceDetectingTextField")
@interface SLBackspaceDetectingTextField : UITextField
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)deleteBackward;
- (void)paste:(id _Nullable)sender;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class UIColor;
@class UIEvent;
SWIFT_CLASS("_TtC26ShopLiveShortformEditorSDK11SLWSTagView")
@interface SLWSTagView : UIView <UITextInputTraits>
@property (nonatomic, strong) UIColor * _Null_unspecified tintColor;
@property (nonatomic) UITextAutocapitalizationType autocapitalizationType;
@property (nonatomic) UITextAutocorrectionType autocorrectionType;
@property (nonatomic) UITextSpellCheckingType spellCheckingType;
@property (nonatomic) UIKeyboardType keyboardType;
@property (nonatomic) UIKeyboardAppearance keyboardAppearance;
@property (nonatomic) UIReturnKeyType returnKeyType;
@property (nonatomic) BOOL enablesReturnKeyAutomatically;
@property (nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (CGSize)sizeThatFits:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (void)layoutSubviews;
@property (nonatomic, readonly) BOOL canBecomeFirstResponder;
- (BOOL)becomeFirstResponder SWIFT_WARN_UNUSED_RESULT;
- (BOOL)resignFirstResponder SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)hitTest:(CGPoint)point withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class NSString;
@interface SLWSTagView (SWIFT_EXTENSION(ShopLiveShortformEditorSDK)) <UIKeyInput>
@property (nonatomic, readonly) BOOL hasText;
- (void)insertText:(NSString * _Nonnull)text;
- (void)deleteBackward;
@end

@class UIFont;
IB_DESIGNABLE
SWIFT_CLASS("_TtC26ShopLiveShortformEditorSDK13SLWSTagsField")
@interface SLWSTagsField : UIScrollView
/// Background color for tag view in normal (non-selected) state.
@property (nonatomic, strong) IBInspectable UIColor * _Null_unspecified tintColor;
/// Text color for tag view in normal (non-selected) state.
@property (nonatomic, strong) IBInspectable UIColor * _Nullable textColor;
/// Background color for tag view in normal (selected) state.
@property (nonatomic, strong) IBInspectable UIColor * _Nullable selectedColor;
/// Text color for tag view in normal (selected) state.
@property (nonatomic, strong) IBInspectable UIColor * _Nullable selectedTextColor;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull delimiter;
@property (nonatomic) IBInspectable BOOL isDelimiterVisible;
/// Whether the text field should tokenize strings automatically when the keyboard is dismissed.
@property (nonatomic) IBInspectable BOOL shouldTokenizeAfterResigningFirstResponder;
@property (nonatomic) IBInspectable CGFloat maxHeight;
/// Max number of lines of tags can display in SLWSTagsField before its contents become scrollable. Default value is 0, which means SLWSTagsField always resize to fit all tags.
@property (nonatomic) IBInspectable NSInteger numberOfLines;
/// Whether or not the SLWSTagsField should become scrollable
@property (nonatomic) IBInspectable BOOL enableScrolling;
@property (nonatomic) IBInspectable CGFloat cornerRadius;
@property (nonatomic) IBInspectable CGFloat borderWidth;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable borderColor;
@property (nonatomic) UIEdgeInsets layoutMargins;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull placeholder;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable placeholderColor;
@property (nonatomic, strong) IBInspectable UIFont * _Nullable placeholderFont;
@property (nonatomic) IBInspectable BOOL placeholderAlwaysVisible;
@property (nonatomic) IBInspectable BOOL readOnly;
@property (nonatomic) UIEdgeInsets contentInset;
@property (nonatomic) IBInspectable CGFloat spaceBetweenTags;
@property (nonatomic) IBInspectable CGFloat spaceBetweenLines;
@property (nonatomic, readonly) BOOL isFirstResponder;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (CGSize)sizeThatFits:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
- (void)layoutSubviews;
- (void)reloadInputViews;
- (void)onTextFieldDidChange:(id _Nonnull)sender;
@end

@interface SLWSTagsField (SWIFT_EXTENSION(ShopLiveShortformEditorSDK))
- (UIView * _Nullable)hitTest:(CGPoint)point withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
@end

@interface SLWSTagsField (SWIFT_EXTENSION(ShopLiveShortformEditorSDK)) <UITextFieldDelegate>
- (BOOL)textFieldShouldBeginEditing:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
- (BOOL)textFieldShouldEndEditing:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidEndEditing:(UITextField * _Nonnull)textField;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
@end

@interface SLWSTagsField (SWIFT_EXTENSION(ShopLiveShortformEditorSDK))
@property (nonatomic, readonly, strong) UIView * _Nullable inputAccessoryView SWIFT_DEPRECATED_MSG("Use 'inputFieldAccessoryView' instead");
@end

@class UIViewController;
@class ShopLiveCommonError;
@class UIImage;
@class ShopliveEditorResultData;
SWIFT_PROTOCOL("_TtP26ShopLiveShortformEditorSDK27ShopLiveCoverPickerDelegate_")
@protocol ShopLiveCoverPickerDelegate
@optional
- (void)onShopLiveCoverPickerErrorWithPicker:(UIViewController * _Nullable)picker error:(ShopLiveCommonError * _Nonnull)error;
- (void)onShopLiveCoverPickerCoverImageSuccessWithPicker:(UIViewController * _Nullable)picker image:(UIImage * _Nullable)image;
- (void)onShopLiveCoverPickerUploadSuccessWithPicker:(UIViewController * _Nullable)picker result:(ShopliveEditorResultData * _Nullable)result;
- (void)onShopLiveCoverPickerCancelledWithPicker:(UIViewController * _Nullable)picker;
- (void)onShopLiveCoverPickerOnEventWithPicker:(UIViewController * _Nullable)picker name:(NSString * _Nonnull)name payload:(NSDictionary<NSString *, id> * _Nullable)payload;
@end

SWIFT_CLASS("_TtC26ShopLiveShortformEditorSDK19ShopLiveMediaPicker")
@interface ShopLiveMediaPicker : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSURL;
SWIFT_PROTOCOL("_TtP26ShopLiveShortformEditorSDK27ShopLiveMediaPickerDelegate_")
@protocol ShopLiveMediaPickerDelegate
@optional
- (void)onShopLiveMediaPickerErrorWithPicker:(UIViewController * _Nullable)picker error:(ShopLiveCommonError * _Nonnull)error;
- (void)onShopLiveMediaPickerDidPickVideoWithPicker:(UIViewController * _Nullable)picker absoluteUrl:(NSURL * _Nonnull)absoluteUrl relativeUrl:(NSURL * _Nonnull)relativeUrl;
- (void)onShopLiveMediaPickerDidPickImageWithPicker:(UIViewController * _Nullable)picker imageUrl:(NSURL * _Nonnull)imageUrl;
- (void)onShopLiveMediaPickerCancelledWithPicker:(UIViewController * _Nullable)picker;
- (void)onShopLiveMediaPickerOnEventWithPicker:(UIViewController * _Nullable)picker name:(NSString * _Nonnull)name payload:(NSDictionary<NSString *, id> * _Nullable)payload;
@end

SWIFT_PROTOCOL("_TtP26ShopLiveShortformEditorSDK31ShopLiveShortformEditorDelegate_")
@protocol ShopLiveShortformEditorDelegate
@optional
- (void)onShopLiveShortformEditorErrorWithError:(ShopLiveCommonError * _Nonnull)error;
- (void)onShopLiveShortformEditorVideoConvertSuccessWithVideoPath:(NSString * _Nonnull)videoPath;
- (void)onShopLiveShortformEditorCoverImageSuccessWithImage:(UIImage * _Nullable)image;
- (void)onShopLiveShortformEditorUploadSuccessWithResult:(ShopliveEditorResultData * _Nullable)result;
- (void)onShopLiveShortformEditorClosed;
- (void)onShopLiveShortformEditorOnEventWithName:(NSString * _Nonnull)name payload:(NSDictionary<NSString *, id> * _Nullable)payload;
@end

@class NSBundle;
SWIFT_CLASS("_TtC26ShopLiveShortformEditorSDK35ShopLiveShortformEditorSDKResources")
@interface ShopLiveShortformEditorSDKResources : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSBundle * _Nonnull bundle;)
+ (NSBundle * _Nonnull)bundle SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC26ShopLiveShortformEditorSDK25ShopLiveShortformUploader")
@interface ShopLiveShortformUploader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_PROTOCOL("_TtP26ShopLiveShortformEditorSDK33ShopLiveShortformUploaderDelegate_")
@protocol ShopLiveShortformUploaderDelegate
@optional
- (void)onShopLiveShortformUploaderOpenVideoEditor;
- (void)onShopLiveShortformUploaderUploadSuccess;
- (void)onShopLiveShortformUploaderPlayPreviewWithRoot:(UIViewController * _Nonnull)root url:(NSString * _Nonnull)url;
- (void)onShopLiveShortformUploaderOpenCoverPickerWithEditor:(UIViewController * _Nullable)editor shortsId:(NSString * _Nonnull)shortsId videoUrl:(NSString * _Nullable)videoUrl;
- (void)onShopLiveShortformUploaderEventWithCommand:(NSString * _Nonnull)command payload:(NSDictionary<NSString *, id> * _Nullable)payload;
- (void)onShopLiveShortformUploaderErrorWithError:(ShopLiveCommonError * _Nonnull)error;
@end

SWIFT_PROTOCOL("_TtP26ShopLiveShortformEditorSDK40ShopLiveShortformUploaderMessageDelegate_")
@protocol ShopLiveShortformUploaderMessageDelegate
@optional
- (void)uploadWithId:(NSString * _Nonnull)id;
- (void)successCoverChange;
@end

SWIFT_PROTOCOL("_TtP26ShopLiveShortformEditorSDK27ShopLiveVideoEditorDelegate_")
@protocol ShopLiveVideoEditorDelegate
@optional
- (void)onShopLiveVideoEditorErrorWithEditor:(UIViewController * _Nullable)editor error:(ShopLiveCommonError * _Nonnull)error;
- (void)onShopLiveVideoEditorVideoConvertSuccessWithEditor:(UIViewController * _Nullable)editor videoPath:(NSString * _Nonnull)videoPath;
- (void)onShopLiveVideoEditorUploadSuccessWithEditor:(UIViewController * _Nullable)editor result:(ShopliveEditorResultData * _Nullable)result;
- (void)onShopLiveVideoEditorCancelledWithEditor:(UIViewController * _Nullable)editor;
- (void)onShopLiveVideoEditorOnEventWithEditor:(UIViewController * _Nullable)editor name:(NSString * _Nonnull)name payload:(NSDictionary<NSString *, id> * _Nullable)payload;
@end

SWIFT_CLASS("_TtC26ShopLiveShortformEditorSDK26ShopLiveVideoUploadPreview")
@interface ShopLiveVideoUploadPreview : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC26ShopLiveShortformEditorSDK24ShopliveEditorResultData")
@interface ShopliveEditorResultData : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
