#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
#ifndef SHOPLIVESDK_SWIFT_H
#define SHOPLIVESDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVKit;
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ShopLiveSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

typedef SWIFT_ENUM(NSInteger, ActionType, open) {
  ActionTypePIP = 0,
  ActionTypeKEEP = 1,
  ActionTypeCLOSE = 2,
};



SWIFT_CLASS("_TtC11ShopLiveSDK12CouponResult")
@interface CouponResult : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC11ShopLiveSDK18CustomActionResult")
@interface CustomActionResult : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end







typedef SWIFT_ENUM(NSInteger, ResultAlertType, open) {
  ResultAlertTypeALERT = 0,
  ResultAlertTypeTOAST = 1,
};

typedef SWIFT_ENUM(NSInteger, ResultStatus, open) {
  ResultStatusSHOW = 0,
  ResultStatusHIDE = 1,
  ResultStatusKEEP = 2,
};

@class UIViewController;
@class NSString;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC11ShopLiveSDK24SLAVPlayerViewController")
@interface SLAVPlayerViewController : AVPlayerViewController
- (void)presentViewController:(UIViewController * _Nonnull)viewControllerToPresent animated:(BOOL)flag completion:(void (^ _Nullable)(void))completion;
- (void)showViewController:(UIViewController * _Nonnull)vc sender:(id _Nullable)sender;
- (void)showDetailViewController:(UIViewController * _Nonnull)vc sender:(id _Nullable)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ShopLiveSDK23SLActivityIndicatorView")
@interface SLActivityIndicatorView : UIActivityIndicatorView
- (nonnull instancetype)initWithActivityIndicatorStyle:(UIActivityIndicatorViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIActivity;

SWIFT_CLASS("_TtC11ShopLiveSDK24SLActivityViewController")
@interface SLActivityViewController : UIActivityViewController
- (nonnull instancetype)initWithActivityItems:(NSArray * _Nonnull)activityItems applicationActivities:(NSArray<UIActivity *> * _Nullable)applicationActivities OBJC_DESIGNATED_INITIALIZER;
- (void)presentViewController:(UIViewController * _Nonnull)viewControllerToPresent animated:(BOOL)flag completion:(void (^ _Nullable)(void))completion;
- (void)showViewController:(UIViewController * _Nonnull)vc sender:(id _Nullable)sender;
- (void)showDetailViewController:(UIViewController * _Nonnull)vc sender:(id _Nullable)sender;
@end


SWIFT_CLASS("_TtC11ShopLiveSDK17SLAlertController")
@interface SLAlertController : UIAlertController
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)presentViewController:(UIViewController * _Nonnull)viewControllerToPresent animated:(BOOL)flag completion:(void (^ _Nullable)(void))completion;
- (void)showViewController:(UIViewController * _Nonnull)vc sender:(id _Nullable)sender;
- (void)showDetailViewController:(UIViewController * _Nonnull)vc sender:(id _Nullable)sender;
@end


SWIFT_CLASS("_TtC11ShopLiveSDK8SLButton")
@interface SLButton : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UICollectionViewLayout;

SWIFT_CLASS("_TtC11ShopLiveSDK16SLCollectionView")
@interface SLCollectionView : UICollectionView
- (nonnull instancetype)initWithFrame:(CGRect)frame collectionViewLayout:(UICollectionViewLayout * _Nonnull)layout OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ShopLiveSDK12SLDatePicker")
@interface SLDatePicker : UIDatePicker
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;

SWIFT_CLASS("_TtC11ShopLiveSDK11SLImageView")
@interface SLImageView : UIImageView
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ShopLiveSDK7SLLabel")
@interface SLLabel : UILabel
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ShopLiveSDK22SLNavigationController")
@interface SLNavigationController : UINavigationController
- (void)pushViewController:(UIViewController * _Nonnull)viewController animated:(BOOL)animated;
- (void)presentViewController:(UIViewController * _Nonnull)viewControllerToPresent animated:(BOOL)flag completion:(void (^ _Nullable)(void))completion;
- (void)showViewController:(UIViewController * _Nonnull)vc sender:(id _Nullable)sender;
- (void)showDetailViewController:(UIViewController * _Nonnull)vc sender:(id _Nullable)sender;
- (nonnull instancetype)initWithNavigationBarClass:(Class _Nullable)navigationBarClass toolbarClass:(Class _Nullable)toolbarClass OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=5.0);
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ShopLiveSDK13SLPageControl")
@interface SLPageControl : UIPageControl
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ShopLiveSDK20SLPageViewController")
@interface SLPageViewController : UIPageViewController
- (void)presentViewController:(UIViewController * _Nonnull)viewControllerToPresent animated:(BOOL)flag completion:(void (^ _Nullable)(void))completion;
- (void)showViewController:(UIViewController * _Nonnull)vc sender:(id _Nullable)sender;
- (void)showDetailViewController:(UIViewController * _Nonnull)vc sender:(id _Nullable)sender;
- (nonnull instancetype)initWithTransitionStyle:(UIPageViewControllerTransitionStyle)style navigationOrientation:(UIPageViewControllerNavigationOrientation)navigationOrientation options:(NSDictionary<UIPageViewControllerOptionsKey, id> * _Nullable)options OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ShopLiveSDK12SLPickerView")
@interface SLPickerView : UIPickerView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class AVPictureInPictureControllerContentSource;

SWIFT_CLASS("_TtC11ShopLiveSDK28SLPictureInPictureController")
@interface SLPictureInPictureController : AVPictureInPictureController
- (nonnull instancetype)initWithContentSource:(AVPictureInPictureControllerContentSource * _Nonnull)contentSource OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=15.0);
@end


SWIFT_CLASS("_TtC11ShopLiveSDK14SLProgressView")
@interface SLProgressView : UIProgressView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ShopLiveSDK12SLScrollView")
@interface SLScrollView : UIScrollView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC11ShopLiveSDK11SLSearchBar")
@interface SLSearchBar : UISearchBar
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ShopLiveSDK18SLSegmentedControl")
@interface SLSegmentedControl : UISegmentedControl
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithItems:(NSArray * _Nullable)items OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ShopLiveSDK8SLSlider")
@interface SLSlider : UISlider
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ShopLiveSDK21SLSplitViewController")
@interface SLSplitViewController : UISplitViewController
- (void)presentViewController:(UIViewController * _Nonnull)viewControllerToPresent animated:(BOOL)flag completion:(void (^ _Nullable)(void))completion;
- (void)showViewController:(UIViewController * _Nonnull)vc sender:(id _Nullable)sender;
- (void)showDetailViewController:(UIViewController * _Nonnull)vc sender:(id _Nullable)sender;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithStyle:(UISplitViewControllerStyle)style OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=14.0);
@end


SWIFT_CLASS("_TtC11ShopLiveSDK11SLStackView")
@interface SLStackView : UIStackView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ShopLiveSDK8SLSwitch")
@interface SLSwitch : UISwitch
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ShopLiveSDK18SLTabBarController")
@interface SLTabBarController : UITabBarController
- (void)presentViewController:(UIViewController * _Nonnull)viewControllerToPresent animated:(BOOL)flag completion:(void (^ _Nullable)(void))completion;
- (void)showViewController:(UIViewController * _Nonnull)vc sender:(id _Nullable)sender;
- (void)showDetailViewController:(UIViewController * _Nonnull)vc sender:(id _Nullable)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ShopLiveSDK11SLTableView")
@interface SLTableView : UITableView
- (nonnull instancetype)initWithFrame:(CGRect)frame style:(UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ShopLiveSDK11SLTextField")
@interface SLTextField : UITextField
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSTextContainer;

SWIFT_CLASS("_TtC11ShopLiveSDK10SLTextView")
@interface SLTextView : UITextView
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * _Nullable)textContainer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC11ShopLiveSDK6SLView")
@interface SLView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ShopLiveSDK16SLViewController")
@interface SLViewController : UIViewController
- (void)viewDidLoad;
- (void)presentViewController:(UIViewController * _Nonnull)viewControllerToPresent animated:(BOOL)flag completion:(void (^ _Nullable)(void))completion;
- (void)showViewController:(UIViewController * _Nonnull)vc sender:(id _Nullable)sender;
- (void)showDetailViewController:(UIViewController * _Nonnull)vc sender:(id _Nullable)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class WKWebViewConfiguration;

SWIFT_CLASS("_TtC11ShopLiveSDK11SLWKWebView")
@interface SLWKWebView : WKWebView
- (nonnull instancetype)initWithFrame:(CGRect)frame configuration:(WKWebViewConfiguration * _Nonnull)configuration OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end

@class UIWindowScene;

SWIFT_CLASS("_TtC11ShopLiveSDK8SLWindow")
@interface SLWindow : UIWindow
- (nonnull instancetype)initWithWindowScene:(UIWindowScene * _Nonnull)windowScene OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=13.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ShopLiveSDK8ShopLive")
@interface ShopLive : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface ShopLive (SWIFT_EXTENSION(ShopLiveSDK))
@end

typedef SWIFT_ENUM(NSInteger, PipPosition, open) {
  PipPositionTopLeft = 0,
  PipPositionTopRight = 1,
  PipPositionBottomLeft = 2,
  PipPositionBottomRight = 3,
  PipPositionDefault = 4,
};

typedef SWIFT_ENUM(NSInteger, PresentationStyle, open) {
  PresentationStyleUnknown = 0,
  PresentationStyleFullScreen = 1,
  PresentationStylePip = 2,
};


@interface ShopLive (SWIFT_EXTENSION(ShopLiveSDK))
@end

typedef SWIFT_ENUM(NSInteger, PlayerMode, open) {
  PlayerModePlay = 0,
  PlayerModePreview = 1,
  PlayerModeNone = 2,
};

typedef SWIFT_ENUM(NSInteger, VideoOrientation, open) {
  VideoOrientationPortrait = 0,
  VideoOrientationLandscape = 1,
  VideoOrientationUnknown = 2,
};

@class UIFont;
@protocol ShopLivePlayerShareDelegate;
@class NSURL;
@class ShopliveWindow;
@class NSNumber;
@class UIColor;
@protocol ShopLiveSDKDelegate;
@class ShopLivePlayerData;
@class ShopLiveCommonUser;
@class ShopLiveInAppPipConfiguration;

@interface ShopLive (SWIFT_EXTENSION(ShopLiveSDK))
+ (void)setEnabledPipSwipeOut:(BOOL)enabled SWIFT_AVAILABILITY(ios,deprecated=0.0.1,message="Will be deprecated soon Use setInAppPipConfiguration(config : ShopLiveInAppPipConfiguration) instead");
+ (void)removeParameterWithKey:(NSString * _Nonnull)key;
+ (void)addParameterWithKey:(NSString * _Nonnull)key value:(NSString * _Nonnull)value;
+ (void)setAdIdWithAdId:(NSString * _Nullable)adId SWIFT_AVAILABILITY(ios,deprecated=0.0.1,message="Will be deprecated soon please Enable AppTrackingTransparency instead");
+ (void)setMixWithOthersWithIsMixAudio:(BOOL)isMixAudio;
+ (void)useCloseButton:(BOOL)use SWIFT_AVAILABILITY(ios,deprecated=0.0.1,message="Will be deprecated soon Use setInAppPipConfiguration(config : ShopLiveInAppPipConfiguration) instead");
+ (void)awakePlayer;
+ (void)setKeepWindowStyleOnReturnFromOsPip:(BOOL)keep;
+ (BOOL)isKeepWindowStyleOnReturnFromOsPip SWIFT_WARN_UNUSED_RESULT;
+ (void)setAppVersion:(NSString * _Nonnull)appVersion;
+ (void)setUsingLocalStorage:(BOOL)use;
+ (BOOL)setPictureInPictureFloatingOffsetWithOffset:(UIEdgeInsets)offset SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)setPictureInPicturePaddingWithPadding:(UIEdgeInsets)padding SWIFT_WARN_UNUSED_RESULT;
+ (void)sendCommandMessageWithCommand:(NSString * _Nonnull)command payload:(NSDictionary<NSString *, id> * _Nullable)payload;
+ (void)setMuteWhenPlayStart:(BOOL)mute;
+ (void)setNextActionOnHandleNavigationWithActionType:(enum ActionType)actionType;
+ (enum ActionType)getNextActionTypeOnHandleNavigation SWIFT_WARN_UNUSED_RESULT;
+ (void)setEndpoint:(NSString * _Nullable)url;
+ (BOOL)isSuccessCampaignJoin SWIFT_WARN_UNUSED_RESULT;
+ (void)setKeepAspectOnTabletPortrait:(BOOL)keep;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SLViewController * _Nullable viewController;)
+ (SLViewController * _Nullable)viewController SWIFT_WARN_UNUSED_RESULT;
+ (void)close;
+ (void)setChatViewFontWithInputBoxFont:(UIFont * _Nullable)inputBoxFont sendButtonFont:(UIFont * _Nullable)sendButtonFont;
+ (void)setShareScheme:(NSString * _Nullable)scheme shareDelegate:(id <ShopLivePlayerShareDelegate> _Nullable)shareDelegate;
+ (void)hookNavigationWithNavigation:(void (^ _Nonnull)(NSURL * _Nonnull))navigation;
+ (void)onTerminated;
+ (void)setKeepPlayVideoOnHeadphoneUnplugged:(BOOL)keepPlay isMute:(BOOL)isMute;
+ (BOOL)isKeepPlayVideoOnHeadPhoneUnplugged SWIFT_WARN_UNUSED_RESULT;
+ (void)setAutoResumeVideoOnCallEnded:(BOOL)autoResume;
+ (BOOL)isAutoResumeVideoOnCallEnded SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersion;)
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) enum PlayerMode playerMode;)
+ (enum PlayerMode)playerMode SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ShopliveWindow * _Nullable playerWindow;)
+ (ShopliveWindow * _Nullable)playerWindow SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) NSNumber * _Nullable fixedPipWidth SWIFT_AVAILABILITY(ios,deprecated=0.0.1,message="Will be deprecated soon use setInAppPipConfiguration(config : ShopLiveInAppPipConfiguration) instead");)
+ (NSNumber * _Nullable)fixedPipWidth SWIFT_WARN_UNUSED_RESULT;
+ (void)setFixedPipWidth:(NSNumber * _Nullable)newValue;
+ (void)mute;
+ (void)unmute;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) enum VideoOrientation orientationMode;)
+ (enum VideoOrientation)orientationMode SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) enum PresentationStyle style;)
+ (enum PresentationStyle)style SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) enum PipPosition pipPosition SWIFT_AVAILABILITY(ios,deprecated=0.0.1,message="Will be deprecated soon use setInAppPipConfiguration(config : ShopLiveInAppPipConfiguration) instead");)
+ (enum PipPosition)pipPosition SWIFT_WARN_UNUSED_RESULT;
+ (void)setPipPosition:(enum PipPosition)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) CGFloat pipScale SWIFT_AVAILABILITY(ios,deprecated=0.0.1,message="Will be deprecated soon use pipMaxSize in setInAppPipConfiguration(config : ShopLiveInAppPipConfiguration) instead");)
+ (CGFloat)pipScale SWIFT_WARN_UNUSED_RESULT;
+ (void)setPipScale:(CGFloat)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull indicatorColor;)
+ (UIColor * _Nonnull)indicatorColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setIndicatorColor:(UIColor * _Nonnull)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) WKWebViewConfiguration * _Nullable webViewConfiguration;)
+ (WKWebViewConfiguration * _Nullable)webViewConfiguration SWIFT_WARN_UNUSED_RESULT;
+ (void)setWebViewConfiguration:(WKWebViewConfiguration * _Nullable)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) id <ShopLiveSDKDelegate> _Nullable delegate;)
+ (id <ShopLiveSDKDelegate> _Nullable)delegate SWIFT_WARN_UNUSED_RESULT;
+ (void)setDelegate:(id <ShopLiveSDKDelegate> _Nullable)newValue;
+ (void)previewWithData:(ShopLivePlayerData * _Nonnull)data completion:(void (^ _Nullable)(void))completion;
+ (void)previewWith:(NSString * _Nullable)campaignKey referrer:(NSString * _Nullable)referrer completion:(void (^ _Nullable)(void))completion SWIFT_AVAILABILITY(ios,deprecated=0.0.1,message="Use preview(data : ShopLivePlayerData) instead");
+ (void)playWithData:(ShopLivePlayerData * _Nonnull)data;
+ (void)playWith:(NSString * _Nullable)campaignKey keepWindowStateOnPlayExecuted:(BOOL)keepWindowStateOnPlayExecuted referrer:(NSString * _Nullable)referrer SWIFT_AVAILABILITY(ios,deprecated=0.0.1,message="Use play(data : ShopLivePlayerData) instead");
+ (void)startPictureInPictureWith:(enum PipPosition)position scale:(CGFloat)scale;
+ (void)startPictureInPicture;
+ (void)stopPictureInPicture;
+ (void)setLoadingAnimationWithImages:(NSArray<UIImage *> * _Nonnull)images;
+ (void)reloadLive;
+ (void)setEnabledPictureInPictureModeWithIsEnabled:(BOOL)isEnabled;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable authToken;)
+ (NSString * _Nullable)authToken SWIFT_WARN_UNUSED_RESULT;
+ (void)setAuthToken:(NSString * _Nullable)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) ShopLiveCommonUser * _Nullable user;)
+ (ShopLiveCommonUser * _Nullable)user SWIFT_WARN_UNUSED_RESULT;
+ (void)setUser:(ShopLiveCommonUser * _Nullable)newValue;
+ (void)configureWith:(NSString * _Nonnull)accessKey;
+ (void)setInAppPipConfigurationWithConfig:(ShopLiveInAppPipConfiguration * _Nonnull)config;
+ (void)setUtmSourceWithUtmSource:(NSString * _Nullable)utmSource;
+ (void)setUtmCampaignWithUtmCampaign:(NSString * _Nullable)utmCampaign;
+ (void)setUtmMediumWithUtmMedium:(NSString * _Nullable)utmMedium;
+ (void)setUtmContentWithUtmContent:(NSString * _Nullable)utmContent;
+ (NSString * _Nullable)getUtmSource SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nullable)getUtmCampaign SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nullable)getUtmMedium SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nullable)getUtmContent SWIFT_WARN_UNUSED_RESULT;
+ (void)setVisibleStatusBarWithIsVisible:(BOOL)isVisible;
+ (BOOL)isVisibleStatusBar SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC11ShopLiveSDK20ShopLiveCouponResult")
@interface ShopLiveCouponResult : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC11ShopLiveSDK26ShopLiveCustomActionResult")
@interface ShopLiveCustomActionResult : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC11ShopLiveSDK29ShopLiveInAppPipConfiguration")
@interface ShopLiveInAppPipConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class ShopLiveInAppPipSize;

SWIFT_CLASS("_TtC11ShopLiveSDK30ShopLiveInAppConfigurationObjc")
@interface ShopLiveInAppConfigurationObjc : ShopLiveInAppPipConfiguration
@property (nonatomic, strong) ShopLiveInAppPipSize * _Nullable _pipSize;
@property (nonatomic) BOOL _useCloseButton;
@property (nonatomic) enum PipPosition _pipPosition;
@property (nonatomic) BOOL _enableSwipeOut;
- (nonnull instancetype)initWithUseCloseButton:(BOOL)useCloseButton pipPosition:(enum PipPosition)pipPosition enableSwipeOut:(BOOL)enableSwipeOut pipSize:(ShopLiveInAppPipSize * _Nonnull)pipSize OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC11ShopLiveSDK20ShopLiveInAppPipSize")
@interface ShopLiveInAppPipSize : NSObject
- (nonnull instancetype)initWithPipMaxSize:(CGFloat)pipMaxSize OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPipFixedWidth:(CGFloat)pipFixedWidth OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPipFixedHeight:(CGFloat)pipFixedHeight OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11ShopLiveSDK11ShopLiveLog")
@interface ShopLiveLog : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, Feature, open) {
  FeatureCLICK = 0,
  FeatureSHOW = 1,
  FeatureACTION = 2,
};


SWIFT_CLASS("_TtC11ShopLiveSDK18ShopLivePlayerData")
@interface ShopLivePlayerData : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11ShopLiveSDK22ShopLivePlayerDataObjc")
@interface ShopLivePlayerDataObjc : ShopLivePlayerData
@property (nonatomic, copy) NSString * _Nonnull _campaignKey;
@property (nonatomic) BOOL _keepWindowStateOnPlayExecuted;
@property (nonatomic, copy) NSString * _Nonnull _referrer;
- (nonnull instancetype)initWithCampaignKey:(NSString * _Nonnull)campaignKey keepWindowStateonPlayExecuted:(BOOL)keepWindowStateonPlayExecuted referrer:(NSString * _Nonnull)referrer OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ShopLiveSDK27ShopLivePlayerShareCampaign")
@interface ShopLivePlayerShareCampaign : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable campaignKey;
@property (nonatomic, readonly, copy) NSString * _Nullable title;
@property (nonatomic, readonly, copy) NSString * _Nullable descriptions;
@property (nonatomic, readonly, copy) NSString * _Nullable thumbnail;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11ShopLiveSDK23ShopLivePlayerShareData")
@interface ShopLivePlayerShareData : NSObject
@property (nonatomic, readonly, strong) ShopLivePlayerShareCampaign * _Nullable campaign;
@property (nonatomic, readonly, copy) NSString * _Nullable url;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP11ShopLiveSDK27ShopLivePlayerShareDelegate_")
@protocol ShopLivePlayerShareDelegate
- (void)handleShareWithData:(ShopLivePlayerShareData * _Nonnull)data;
@end

typedef SWIFT_ENUM(NSInteger, ShopLiveResultAlertType, open) {
  ShopLiveResultAlertTypeALERT = 0,
  ShopLiveResultAlertTypeTOAST = 1,
};

typedef SWIFT_ENUM(NSInteger, ShopLiveResultStatus, open) {
  ShopLiveResultStatusSHOW = 0,
  ShopLiveResultStatusHIDE = 1,
  ShopLiveResultStatusKEEP = 2,
};


SWIFT_PROTOCOL("_TtP11ShopLiveSDK19ShopLiveSDKDelegate_")
@protocol ShopLiveSDKDelegate
- (void)handleNavigationWith:(NSURL * _Nonnull)url;
@optional
- (void)handleDownloadCouponResultWith:(NSString * _Nonnull)couponId completion:(void (^ _Nonnull)(CouponResult * _Nonnull))completion SWIFT_DEPRECATED_MSG("use handleDownloadCoupon(with couponId: String, result: @escaping (ShopLiveCouponResult) -> Void) instead");
- (void)handleDownloadCouponWith:(NSString * _Nonnull)couponId result:(void (^ _Nonnull)(ShopLiveCouponResult * _Nonnull))result;
- (void)handleDownloadCouponWith:(NSString * _Nonnull)couponId completion:(void (^ _Nonnull)(void))completion SWIFT_DEPRECATED_MSG("use handleDownloadCoupon(with couponId: String, result: @escaping (ShopLiveCouponResult) -> Void) instead");
- (void)handleCustomActionResultWith:(NSString * _Nonnull)id type:(NSString * _Nonnull)type payload:(id _Nullable)payload completion:(void (^ _Nonnull)(CustomActionResult * _Nonnull))completion SWIFT_DEPRECATED_MSG("use handleCustomAction(with id: String, type: String, payload: Any?, result: @escaping (ShopLiveCustomActionResult) -> Void) instead");
- (void)handleCustomActionWith:(NSString * _Nonnull)id type:(NSString * _Nonnull)type payload:(id _Nullable)payload completion:(void (^ _Nonnull)(void))completion SWIFT_DEPRECATED_MSG("use handleCustomAction(with id: String, type: String, payload: Any?, result: @escaping (ShopLiveCustomActionResult) -> Void) instead");
- (void)handleCustomActionWith:(NSString * _Nonnull)id type:(NSString * _Nonnull)type payload:(id _Nullable)payload result:(void (^ _Nonnull)(ShopLiveCustomActionResult * _Nonnull))result;
- (void)handleChangeCampaignStatusWithStatus:(NSString * _Nonnull)status;
- (void)handleChangedPlayerStatusWithStatus:(NSString * _Nonnull)status;
- (void)handleErrorWithCode:(NSString * _Nonnull)code message:(NSString * _Nonnull)message;
- (void)handleCampaignInfoWithCampaignInfo:(NSDictionary<NSString *, id> * _Nonnull)campaignInfo;
- (void)handleCommand:(NSString * _Nonnull)command with:(id _Nullable)payload;
- (void)onSetUserName:(NSDictionary<NSString *, id> * _Nonnull)payload;
- (void)handleReceivedCommand:(NSString * _Nonnull)command with:(id _Nullable)payload;
- (void)playerPanGestureWithState:(UIGestureRecognizerState)state position:(CGPoint)position;
- (void)logWithName:(NSString * _Nonnull)name feature:(enum Feature)feature campaign:(NSString * _Nonnull)campaign parameter:(NSDictionary<NSString *, NSString *> * _Nonnull)parameter SWIFT_DEPRECATED_MSG("use log(name: String, feature: ShopLiveLog.Feature, campaign: String, payload: [String: Any]) instead");
- (void)logWithName:(NSString * _Nonnull)name feature:(enum Feature)feature campaign:(NSString * _Nonnull)campaign payload:(NSDictionary<NSString *, id> * _Nonnull)payload;
@end

typedef SWIFT_ENUM(NSInteger, ShopLiveViewTrackEvent, open) {
  ShopLiveViewTrackEventViewWillDisAppear = 0,
  ShopLiveViewTrackEventViewDidDisAppear = 1,
  ShopLiveViewTrackEventPipWillAppear = 2,
  ShopLiveViewTrackEventPipDidAppear = 3,
  ShopLiveViewTrackEventFullScreenWillAppear = 4,
  ShopLiveViewTrackEventFullScreenDidAppear = 5,
};


SWIFT_CLASS("_TtC11ShopLiveSDK14ShopliveWindow")
@interface ShopliveWindow : SLWindow
- (void)addSubview:(UIView * _Nonnull)view;
- (nonnull instancetype)initWithWindowScene:(UIWindowScene * _Nonnull)windowScene OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=13.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end










#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
