//
//  EventTrace.swift
//  ShopLiveShortformEditorSDK
//
//  Created by sangmin han on 11/22/24.
//  Copyright © 2024 com.app. All rights reserved.
//

import Foundation



enum EventTrace : String {
    case MEDIA_PICKER_CLICK_CLOSE = "MEDIA_PICKER_CLICK_CLOSE"
    case MEDIA_PICKER_CLICK_CONFIRM = "MEDIA_PICKER_CLICK_CONFIRM"
    
    case VIDEO_EDITOR_CLICK_CLOSE = "VIDEO_EDITOR_CLICK_CLOSE"
    case VIDEO_EDITOR_CLICK_CONFIRM = "VIDEO_EDITOR_CLICK_CONFIRM"
    
    case VIDEO_EDITOR_CLICK_VOLUME = "VIDEO_EDITOR_CLICK_VOLUME"
    case VIDEO_EDITOR_CLICK_VOLUME_CANCEL = "VIDEO_EDITOR_CLICK_VOLUME_CANCEL"
    case VIDEO_EDITOR_CLICK_VOLUME_CONFIRM = "VIDEO_EDITOR_CLICK_VOLUME_CONFIRM"
    
    case VIDEO_EDITOR_CLICK_CROP = "VIDEO_EDITOR_CLICK_CROP"
    case VIDEO_EDITOR_CLICK_CROP_CANCEL = "VIDEO_EDITOR_CLICK_CROP_CANCEL"
    case VIDEO_EDITOR_CLICK_CROP_CONFIRM = "VIDEO_EDITOR_CLICK_CROP_CONFIRM"
    
    
    case VIDEO_EDITOR_CLICK_FILTER = "VIDEO_EDITOR_CLICK_FILTER"
    case VIDEO_EDITOR_CLICK_FILTER_CANCEL = "VIDEO_EDITOR_CLICK_FILTER_CANCEL"
    case VIDEO_EDITOR_CLICK_FILTER_CONFIRM = "VIDEO_EDITOR_CLICK_FILTER_CONFIRM"
    
    case VIDEO_EDITOR_CLICK_PLAYBACK_SPEED = "VIDEO_EDITOR_CLICK_PLAYBACK_SPEED"
    case VIDEO_EDITOR_CLICK_PLAYBACK_SPEED_CANCEL = "VIDEO_EDITOR_CLICK_PLAYBACK_SPEED_CANCEL"
    case VIDEO_EDITOR_CLICK_PLAYBACK_SPEED_CONFIRM = "VIDEO_EDITOR_CLICK_PLAYBACK_SPEED_CONFIRM"
    
    case COVER_PICKER_CLICK_CAMERA_ROLL = "COVER_PICKER_CLICK_CAMERA_ROLL"
    case COVER_PICKER_CLICK_CLOSE = "COVER_PICKER_CLICK_CLOSE"
    case COVER_PICKER_CLICK_CONFIRM = "COVER_PICKER_CLICK_CONFIRM"
}
