
# This is a basic workflow to help you get started with Actions

name: pull_request_action
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches:
      - "**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    env:
      TITLE: ${{ github.event.pull_request.title }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: GET TITLE
        run: |
            echo "PULL_REQUEST_TITLE: $TITLE"
    
      - uses: actions/checkout@v3
      - uses: jdx/mise-action@v2
      
      - name: check xcode command line tool
        run: |
            /usr/bin/xcodebuild -version
      
      - name: check_tuist_installed
        run: |
            tuist version
            
      - name: tuist install
        run: |
            mise install tuist
            
      - name: tuist fetch
        run: |
            tuist fetch
    
      # tusit generate
      - name: tuist player generate
        if: "contains(env.TITLE, 'PLAYER')"
        run: |
            TUIST_GENTYPE=PLAYERDEMO tuist generate --no-open
        
      - name: tuist shortform generate
        if: "contains(env.TITLE, 'SHORTFORM')"
        run: |
            TUIST_GENTYPE=SHORTFORMDEMO tuist generate --no-open
    
      - name: tuist common generate
        if: "contains(env.TITLE,'COMMON')"
        run: |
            TUIST_GENTYPE=COMMON tuist generate --no-open
      - name: tuist editor generate
        if: "contains(env.TITLE, 'EDITOR')"
        run: |
            TUIST_GENTYPE=EDITOR tuist generate --no-open
      
      - name: tuist all generate
        if: "contains(env.TITLE,'ALL')"
        run: |
            tuist generate --no-open
     
      
      # Runs a set of commands using the runners shell
      - name: xcode player build
        if: "contains(env.TITLE, 'PLAYER')"
        run: |
            echo building shoplive
            xcodebuild -workspace  "ShopLive.xcworkspace" -scheme "ShopLiveSDK" -destination 'platform=iOS Simulator,name=iPhone 14 Pro'
        
      - name: xcode shortform build
        if: "contains(env.TITLE, 'SHORTFORM')"
        run: |
            echo building shoplive
            xcodebuild -workspace  "ShopLive.xcworkspace" -scheme "ShopLiveShortformSDK" -destination 'platform=iOS Simulator,name=iPhone 14 Pro'
    
      - name: xcode common build
        if: "contains(env.TITLE, 'COMMON')"
        run: |
            echo building shoplive
            xcodebuild -workspace  "ShopLive.xcworkspace" -scheme "ShopliveSDKCommon" -destination 'platform=iOS Simulator,name=iPhone 14 Pro'
      
      - name: xcode editor build
        if: "contains(env.TITLE, 'EDITOR')"
        run: |
            echo building shoplive
            xcodebuild -workspace  "ShopLive.xcworkspace" -scheme "ShopLiveShortformEditorSDK" -destination 'platform=iOS Simulator,name=iPhone 14 Pro'
            
      - name: xcode all build
        if: "contains(env.TITLE, 'ALL')"
        run: |
            xcodebuild -workspace  "ShopLive.xcworkspace" -scheme "ShopLiveDemo" -destination 'platform=iOS Simulator,name=iPhone 14 Pro'
        
    
